export {
  ENERGY_MAX,
  ENERGY_PER_HOUR,
  ENERGY_REGEN_MS,
  MAX_BUILDING_LEVEL,
  PHASE1_BUILDINGS,
  PHASE_BUILDINGS,
  SUMMONER_EXP_PER_LEVEL,
  addSummonerExp,
  buildingUpgradeManaCost,
  canUpgradeBuilding,
  collectCrystal,
  collectMana,
  createStarterIsland,
  energyRegenRemainingMs,
  hasBuilding,
  productionCrystalCap,
  productionCrystalPerHour,
  productionManaPerHour,
  productionStorageCap,
  runWish,
  spendEnergy,
  syncBuildingUnlocks,
  tickProduction,
  todayKey,
  upgradeBuilding,
} from "./island.js";
export type { BuildingDef, BuildingId, BuildingInstance, IslandState } from "./island.js";
